version: "3.8"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: video
    deploy:
      placement:
        max_replicas_per_node: 1
  video-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: video
    ports:
      - "8080:8080"